// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// GPcovar
NumericMatrix GPcovar(const NumericMatrix& X, const NumericVector& dsq_eta);
RcppExport SEXP _MCMChybridGP_GPcovar(SEXP XSEXP, SEXP dsq_etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type dsq_eta(dsq_etaSEXP);
    rcpp_result_gen = Rcpp::wrap(GPcovar(X, dsq_eta));
    return rcpp_result_gen;
END_RCPP
}
// Leap
NumericMatrix Leap(const NumericMatrix& X, const NumericVector& y, NumericVector x, NumericVector p, int L, double delta, const NumericMatrix& Sigma_inv, const NumericVector& dsq_eta, double T, double maxsig, const NumericVector& lb, const NumericVector& ub);
RcppExport SEXP _MCMChybridGP_Leap(SEXP XSEXP, SEXP ySEXP, SEXP xSEXP, SEXP pSEXP, SEXP LSEXP, SEXP deltaSEXP, SEXP Sigma_invSEXP, SEXP dsq_etaSEXP, SEXP TSEXP, SEXP maxsigSEXP, SEXP lbSEXP, SEXP ubSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Sigma_inv(Sigma_invSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type dsq_eta(dsq_etaSEXP);
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type maxsig(maxsigSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ub(ubSEXP);
    rcpp_result_gen = Rcpp::wrap(Leap(X, y, x, p, L, delta, Sigma_inv, dsq_eta, T, maxsig, lb, ub));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MCMChybridGP_GPcovar", (DL_FUNC) &_MCMChybridGP_GPcovar, 2},
    {"_MCMChybridGP_Leap", (DL_FUNC) &_MCMChybridGP_Leap, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_MCMChybridGP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
