# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GPcovar <- function(X, dsq_eta) {
    .Call(`_MCMChybridGP_GPcovar`, X, dsq_eta)
}

Leap <- function(X, y, x, p, L, delta, Sigma_inv, dsq_eta, T, maxsig, lb, ub) {
    .Call(`_MCMChybridGP_Leap`, X, y, x, p, L, delta, Sigma_inv, dsq_eta, T, maxsig, lb, ub)
}

